apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: rdthomashoutekier/multi-client
      context: client
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: rdthomashoutekier/multi-server
      context: server
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    - image: rdthomashoutekier/multi-worker
      context: worker
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yml
      - k8s/server-deployment.yml
      - k8s/worker-deployment.yml
      - k8s/server-cluster-ip-service.yml
      - k8s/client-cluster-ip-service.yml