apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: k8s-houtekier-be-tls
spec:
    secretName: k8s-houtekier-be
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: k8s.houtekier.be
    dnsNames:
        - k8s.houtekier.be
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - k8s.houtekier.be